### ISSUE TITLE
Problematic background goroutine leak on every call to validateRequest function

### ISSUE THREAD

**Issue by MicahParks** [benc-uk/go-rest-api#1]
In the `validateRequest` function in this block of code:
https://github.com/benc-uk/go-rest-api/blob/5f863a3793f1db3bb9d6ce02aaa59b1a105487a2/pkg/auth/auth.go#L102-L104

The `*keyfunc.JWKS` is created with the option:
```
RefreshInterval: time.Duration(1) * time.Hour,
```

This means a background goroutine will be launched to refresh the remote JWK Set resource. This background goroutine will perform an HTTP GET once an hour, forever. As calls to the `validateRequest` occur, this effect will compound linearly. If this function is called 100 times then 100 different background goroutines will perform that HTTP GET per hour.

I would recommend one of two things:
1. Remove all fields from the `keyfunc.Options` argument. An empty data structure is valid and will not launch any background goroutines or perform caching.
2. Perform the `keyfunc.Get` method call outside of this function and save the returned `*keyfunc.JWKS` to be reused across calls. This will keep only 1 background goroutine with caching. Make sure to call the [`EndBackground`](https://pkg.go.dev/github.com/MicahParks/keyfunc#JWKS.EndBackground) method when the `*keyfunc.JWKS` is no longer used or pass in a `context.Context` to the [`keyfunc.Options`](https://pkg.go.dev/github.com/MicahParks/keyfunc#Options) `Ctx` field.

**Comment by benc-uk** [comment]
Wow this issue slipped me by!
Totally makes sense, I'll get this fixed in next release
